export const GET_DATA_UNGVIEN_DETAIL = 'GET_DATA_UNGVIEN_DETAIL';
export const GET_DATA_UNGVIEN_DETAIL_SUCCESS = 'GET_DATA_UNGVIEN_DETAIL_SUCCESS';
export const GET_DATA_UNGVIEN_DETAIL_FALSE = 'GET_DATA_UNGVIEN_DETAIL_FALSE';

export const SAVE_UNGVIEN = 'SAVE_UNGVIEN';