export const GET_DATA_UNGVIEN_DETAIL = 'GET_DATA_UNGVIEN_DETAIL';
export const GET_DATA_UNGVIEN_DETAIL_SUCCESS = 'GET_DATA_UNGVIEN_DETAIL_SUCCESS';
export const GET_DATA_UNGVIEN_DETAIL_FALSE = 'GET_DATA_UNGVIEN_DETAIL_FALSE';
export const GET_DATA_HISTORY = 'GET_DATA_HISTORY';
export const GET_DATA_GIAIDOAN = 'GET_DATA_GIAIDOAN';
export const SAVE_UNGVIEN = 'SAVE_UNGVIEN';
export const TRANFER_UNGVIEN = 'TRANFER_UNGVIEN';