export const GET_DATA_CAMPAIGN_DETAIL = 'GET_DATA_CAMPAIGN_DETAIL';
export const GET_DATA_CAMPAIGN_DETAIL_SUCCESS = 'GET_DATA_CAMPAIGN_DETAIL_SUCCESS';
export const GET_DATA_CAMPAIGN_DETAIL_FALSE = 'GET_DATA_CAMPAIGN_DETAIL_FALSE';

export const SAVE_CAMPAIGN = 'SAVE_CAMPAIGN';
export const CHECK_SAVE_CAMPAIGN = 'CHECK_SAVE_CAMPAIGN';
