export const GET_DATA_UNGVIEN_DETAIL = 'GET_DATA_UNGVIEN_DETAIL2';
export const GET_DATA_UNGVIEN_DETAIL_SUCCESS = 'GET_DATA_UNGVIEN_DETAIL_SUCCESS2';
export const GET_DATA_UNGVIEN_DETAIL_FALSE = 'GET_DATA_UNGVIEN_DETAIL_FALSE2';
export const SAVE_UNGVIEN = 'SAVE_UNGVIEN2';