export const GET_DATA_UNGVIEN_DETAIL = 'GET_DATA_UNGVIEN_DETAIL111';
export const GET_DATA_UNGVIEN_DETAIL_SUCCESS = 'GET_DATA_UNGVIEN_DETAIL_SUCCESS111';
export const GET_DATA_UNGVIEN_DETAIL_FALSE = 'GET_DATA_UNGVIEN_DETAIL_FALSE111';
export const GET_DATA_HISTORY = 'GET_DATA_HISTORY111';
export const SAVE_UNGVIEN = 'SAVE_UNGVIEN111';