export const GET_DATA_UNGVIEN= 'GET_DATA_UNGVIEN';
export const GET_DATA_UNGVIEN_SUCCESS = 'GET_DATA_UNGVIEN_SUCCESS';
export const GET_DATA_UNGVIEN_FALSE = 'GET_DATA_UNGVIEN_FALSE';

export const GET_DATA_CAMPAIGN = 'GET_DATA_CAMPAIGN2';
export const GET_DATA_CAMPAIGN_SUCCESS = 'GET_DATA_CAMPAIGN_SUCCESS2';
export const GET_DATA_CAMPAIGN_FALSE = 'GET_DATA_CAMPAIGN_FALSE2';


