export const GET_DATA_CAMPAIGN = 'GET_DATA_CAMPAIGN';
export const GET_DATA_CAMPAIGN_SUCCESS = 'GET_DATA_CAMPAIGN_SUCCESS';
export const GET_DATA_CAMPAIGN_FALSE = 'GET_DATA_CAMPAIGN_FALSE';
export const TO_THEM_CHIEN_DICH = 'TO_THEM_CHIEN_DICH';

export const DELETE_DATA_CAMPAIGN = 'GET_DATA_CAMPAIGN';
