export const GET_DATA_NOT_UNGVIEN = 'GET_DATA_NOT_UNGVIEN';
export const GET_DATA_UNGVIEN_DETAIL_SUCCESS = 'GET_DATA_UNGVIEN_DETAIL_SUCCESS';
export const GET_DATA_UNGVIEN_DETAIL_FALSE = 'GET_DATA_UNGVIEN_DETAIL_FALSE';

export const ADD_UNGVIEN = 'ADD_UNGVIEN';